pipeline:

  web_tests_then_build_dist:
    image: quay.io/ukhomeofficedigital/nodejs-base:v6.9.1
    commands:
      - yum install -y git bzip2 bzip2-libs fontconfig
      - git config --global url."https://".insteadOf git://
      - npm install -g yarn@0.27.5
      - cd platform-hub-web
      - rm -rf node_modules
      - yarn
      - yarn run test
      - yarn run build
    when:
      event: [push, tag]

  # Expects the optimized dist code to have been built
  web_build_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-web
      - docker build -t platform-hub-web:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  web_test_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -t --rm --name platform-hub-web-test platform-hub-web:${DRONE_COMMIT_SHA} sh -c "cd /app; ls -lah; test -e index.html"
    when:
      event: [push, tag]

  web_latest_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:latest
    when:
      event: push
      branch: master

  web_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
    when:
      event: tag


  api_tests:
    image: alpine:3.5
    environment:
      - SECRET_KEY_BASE=$(head -c30 < /dev/urandom | base64)
      - PHUB_DB_HOST=postgres
      - GITHUB_CLIENT_ID=NA
      - GITHUB_CLIENT_SECRET=NA
      - AGENT_GITHUB_TOKEN=noop
      - AGENT_GITHUB_ORG=noop
      - AGENT_GITHUB_ORG_MAIN_TEAM_ID=noop
      - AGENT_KEYCLOAK_CLIENT_ID=noop
      - AGENT_KEYCLOAK_CLIENT_SECRET=noop
      - AGENT_KEYCLOAK_USERNAME=noop
      - AGENT_KEYCLOAK_PASSWORD=noop
      - AGENT_KEYCLOAK_BASE_URL=noop
      - AGENT_KEYCLOAK_REALM=noop
      - APP_BASE_URL="http://localhost:3000"
      - EMAIL_FROM_ADDRESS="test@example.org"
      - EMAIL_MAX_TO_ADDRESSES=10
      - SLACK_WEBHOOK=noop
      - FILESTORE_S3_REGION=eu-west-2
      - FILESTORE_S3_BUCKET_NAME=noop
      - FILESTORE_S3_ACCESS_KEY_ID=noop
      - FILESTORE_S3_SECRET_ACCESS_KEY=noop
    commands:
      - apk update && apk upgrade
      - apk --update add ca-certificates openssl
      - update-ca-certificates
      - apk --update add bash ruby ruby-irb ruby-rake ruby-io-console ruby-json ruby-bigdecimal libstdc++ tzdata postgresql-client
      - apk --update add build-base ruby-dev libc-dev libressl-dev postgresql-dev libffi-dev zlib-dev
      - "echo 'gem: --no-document' > /etc/gemrc && gem install bundler -v 1.16.2"
      - cd platform-hub-api
      - "/bin/bash -c 'bundle install --jobs 20 --retry 5 --deployment --no-cache'"
      - "/bin/bash -c 'bin/setup && bundle exec rspec'"
    when:
      event: [push, tag]

  api_build_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-api
      - docker build -t platform-hub-api:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  api_test_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - PORT=6055
      - POSTGRES_USER=phub
      - POSTGRES_PASSWORD=phub_password
    commands:
      - >
          docker run
          -d
          --name phub-api-postgres-${DRONE_BUILD_NUMBER}
          -e POSTGRES_USER
          -e POSTGRES_PASSWORD
          postgres:9.6.1
      - sleep 5
      - 'until docker exec -e POSTGRES_USER -e POSTGRES_PASSWORD phub-api-postgres-${DRONE_BUILD_NUMBER} psql -U $${POSTGRES_USER} -c "select 1" > /dev/null 2>&1; do sleep 2; done'
      - >
          docker run
          --name platform-hub-api-test
          -t --rm
          --link phub-api-postgres-${DRONE_BUILD_NUMBER}:phub-postgres-${DRONE_BUILD_NUMBER}
          -e PORT
          -e PHUB_DB_HOST=phub-postgres-${DRONE_BUILD_NUMBER}
          -e PHUB_DB_NAME=phub_development
          -e PHUB_DB_USERNAME=$${POSTGRES_USER}
          -e PHUB_DB_PASSWORD=$${POSTGRES_PASSWORD}
          -e RAILS_LOG_TO_STDOUT=true
          -e SECRET_KEY_BASE=$(head -c30 < /dev/urandom | base64)
          -e GITHUB_CLIENT_ID=NA
          -e GITHUB_CLIENT_SECRET=NA
          -e AGENT_GITHUB_TOKEN=noop
          -e AGENT_GITHUB_ORG=noop
          -e AGENT_GITHUB_ORG_MAIN_TEAM_ID=noop
          -e AGENT_KEYCLOAK_CLIENT_ID=noop
          -e AGENT_KEYCLOAK_CLIENT_SECRET=noop
          -e AGENT_KEYCLOAK_USERNAME=noop
          -e AGENT_KEYCLOAK_PASSWORD=noop
          -e AGENT_KEYCLOAK_BASE_URL=noop
          -e AGENT_KEYCLOAK_REALM=noop
          -e APP_BASE_URL="http://localhost:$${PORT}"
          -e EMAIL_FROM_ADDRESS="test@example.org"
          -e EMAIL_MAX_TO_ADDRESSES=10
          -e SLACK_WEBHOOK=noop
          -e FILESTORE_S3_REGION=eu-west-2
          -e FILESTORE_S3_BUCKET_NAME=noop
          -e FILESTORE_S3_ACCESS_KEY_ID=noop
          -e FILESTORE_S3_SECRET_ACCESS_KEY=noop
          platform-hub-api:${DRONE_COMMIT_SHA}
          /bin/bash -c "cd /app; bin/setup && bin/rails server -d; sleep 5; curl -s -f http://127.0.0.1:$${PORT}/healthz"
      - docker kill phub-api-postgres-${DRONE_BUILD_NUMBER}
      - docker rm -f phub-api-postgres-${DRONE_BUILD_NUMBER}
    when:
      event: [push, tag]

  api_latest_image_to_quay:
    image: docker:17.10.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:latest
    when:
      event: push
      branch: master

  api_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
    when:
      event: tag

services:

  postgres:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=phub
      - POSTGRES_PASSWORD=phub_password
