pipeline:

  web_tests_then_build_dist:
    image: quay.io/ukhomeofficedigital/nodejs-base:v6.9.1
    commands:
      - yum install -y git bzip2 bzip2-libs fontconfig
      - git config --global url."https://".insteadOf git://
      - npm install -g yarn@0.27.5
      - cd platform-hub-web
      - rm -rf node_modules
      - yarn
      - yarn run test
      - yarn run build
    when:
      event: [push, tag]

  # Expects the optimized dist code to have been built
  web_build_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-web
      - docker build -t platform-hub-web:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  web_test_image:
    image: platform-hub-web:${DRONE_COMMIT_SHA}
    commands:
      - cd /app
      - ls -lah
      - test -e index.html
    when:
      event: [push, tag]

  web_latest_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:latest
    when:
      event: push
      branch: master

  web_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
    when:
      event: tag


  api_tests:
    image: alpine:3.5
    environment:
      - SECRET_KEY_BASE=$(head -c30 < /dev/urandom | base64)
      - PHUB_DB_HOST=postgres
      - GITHUB_CLIENT_ID=NA
      - GITHUB_CLIENT_SECRET=NA
      - AGENT_GITHUB_TOKEN=noop
      - AGENT_GITHUB_ORG=noop
      - AGENT_GITHUB_ORG_MAIN_TEAM_ID=noop
      - AGENT_KEYCLOAK_CLIENT_ID=noop
      - AGENT_KEYCLOAK_CLIENT_SECRET=noop
      - AGENT_KEYCLOAK_USERNAME=noop
      - AGENT_KEYCLOAK_PASSWORD=noop
      - AGENT_KEYCLOAK_BASE_URL=noop
      - AGENT_KEYCLOAK_REALM=noop
      - APP_BASE_URL="http://localhost:3000"
      - EMAIL_FROM_ADDRESS="test@example.org"
      - EMAIL_MAX_TO_ADDRESSES=10
      - SLACK_WEBHOOK=noop
    commands:
      - apk update && apk upgrade
      - apk --update add ca-certificates openssl
      - update-ca-certificates
      - apk --update add bash ruby ruby-irb ruby-rake ruby-io-console ruby-json ruby-bigdecimal libstdc++ tzdata postgresql-client
      - apk --update add build-base ruby-dev libc-dev postgresql-dev libxml2-dev libxslt-dev libffi-dev
      - "echo 'gem: --no-document' > /etc/gemrc && gem install bundler -v 1.14.6"
      - cd platform-hub-api
      - "/bin/bash -c 'bundle install --jobs 20 --retry 5 --deployment --no-cache'"
      - "/bin/bash -c 'bin/setup && bundle exec rspec'"
    when:
      event: [push, tag]

  api_build_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-api
      - docker build -t platform-hub-api:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  api_test_image:
    image: platform-hub-api:${DRONE_COMMIT_SHA}
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - PORT=6055
      - PHUB_DB_HOST=postgres
      - PHUB_DB_NAME=phub_development
      - PHUB_DB_USERNAME=phub
      - PHUB_DB_PASSWORD=phub_password
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=$(head -c30 < /dev/urandom | base64)
      - GITHUB_CLIENT_ID=NA
      - GITHUB_CLIENT_SECRET=NA
      - AGENT_GITHUB_TOKEN=noop
      - AGENT_GITHUB_ORG=noop
      - AGENT_GITHUB_ORG_MAIN_TEAM_ID=noop
      - AGENT_KEYCLOAK_CLIENT_ID=noop
      - AGENT_KEYCLOAK_CLIENT_SECRET=noop
      - AGENT_KEYCLOAK_USERNAME=noop
      - AGENT_KEYCLOAK_PASSWORD=noop
      - AGENT_KEYCLOAK_BASE_URL=noop
      - AGENT_KEYCLOAK_REALM=noop
      - APP_BASE_URL="http://localhost:$${PORT}"
      - EMAIL_FROM_ADDRESS="test@example.org"
      - EMAIL_MAX_TO_ADDRESSES=10
      - SLACK_WEBHOOK=noop
    commands:
      - cd /app
      - bin/rails server &
      - sleep 5
      - curl -s -f http://127.0.0.1:$${PORT}/healthz
    when:
      event: [push, tag]

  api_latest_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:latest
    when:
      event: push
      branch: master

  api_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
    when:
      event: tag

services:

  postgres:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=phub
      - POSTGRES_PASSWORD=phub_password
