pipeline:

  web_tests_then_build_dist:
    image: quay.io/ukhomeofficedigital/nodejs-base:v6.9.1
    commands:
      - yum install -y git bzip2 bzip2-libs fontconfig
      - git config --global url."https://".insteadOf git://
      - npm install -g yarn@0.27.5
      - cd platform-hub-web
      - rm -rf node_modules
      - yarn
      - yarn run test
      - yarn run build
    when:
      event: [push, tag]

  # Expects the optimized dist code to have been built
  web_build_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-web
      - docker build -t platform-hub-web:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  web_test_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -t --rm --name platform-hub-web-test platform-hub-web:${DRONE_COMMIT_SHA} sh -c "cd /app; ls -lah; test -e index.html"
    when:
      event: [push, tag]

  web_scan_image:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: platform-hub-web:${DRONE_COMMIT_SHA}
    when:
      event: [push, tag]

  web_latest_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:latest
    when:
      event: push
      branch: master

  web_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-web:$${DRONE_TAG}
    when:
      event: tag

  api_tests:
    image: ruby:2.3.8-alpine
    environment:
      - PHUB_DB_HOST=postgres
    commands:
      - apk -U add ca-certificates libressl postgresql-client postgresql-dev build-base make
      - update-ca-certificates
      - "echo 'gem: --no-document' > /etc/gemrc && gem install bundler -v 1.16.2"
      - cd platform-hub-api
      - bundle install --jobs 20 --retry 5 --deployment
      - ./test.sh
    when:
      event: [push, tag]

  api_build_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd platform-hub-api
      - docker build -t platform-hub-api:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  api_test_image:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - POSTGRES_USER=phub
      - POSTGRES_PASSWORD=phub_password
    commands:
      - docker run -d -p 5432:5432 --name phub-api-postgres-${DRONE_BUILD_NUMBER} -e POSTGRES_USER -e POSTGRES_PASSWORD postgres:9.6.1
      - sleep 5
      - 'until docker exec -e POSTGRES_USER -e POSTGRES_PASSWORD phub-api-postgres-${DRONE_BUILD_NUMBER} psql -U $${POSTGRES_USER} -c "select 1" > /dev/null 2>&1; do sleep 2; done'
      - >
          docker run
          --name phub-api-${DRONE_BUILD_NUMBER}
          -t --rm --env-file=platform-hub-api/.env.test
          -e PHUB_DB_HOST=phub-api-postgres-${DRONE_BUILD_NUMBER}
          --link phub-api-postgres-${DRONE_BUILD_NUMBER}
          platform-hub-api:${DRONE_COMMIT_SHA}
          /bin/bash -c "cd /app; bin/setup; bin/rails server -d; sleep 5; curl -s -f http://127.0.0.1:3000/healthz"
    when:
      event: [push, tag]

  cleanup_postgres:
    image: docker:17.10.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker rm -f phub-api-postgres-${DRONE_BUILD_NUMBER}
    when:
      event: [push, tag]
      status: [success, failure]

  api_scan_image:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: platform-hub-api:${DRONE_COMMIT_SHA}
    whitelist: CVE-2019-5419,CVE-2019-5420,CVE-2020-8130
    when:
      event: [push, tag]

  api_latest_image_to_quay:
    image: docker:17.10.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:latest
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:latest
    when:
      event: push
      branch: master

  api_tag_image_to_quay:
    image: docker:17.07.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+platform_hub" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag platform-hub-api:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/platform-hub-api:$${DRONE_TAG}
    when:
      event: tag

services:
  postgres:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=phub
      - POSTGRES_PASSWORD=phub_password
