services:
  web:
    build:
      context: platform-hub-web
      dockerfile: web.Dockerfile
    ports:
      - 3000:3000

  # api:
  #   build:
  #     context: platform-hub-api
  #     dockerfile: api.Dockerfile
  #   ports:
  #     - 8080:8080