#!/usr/bin/env bash

set -e

# shellcheck source=/dev/null
source "$(dirname ${0})/.env"

echo "Starting up existing keycloak-proxy container '${PHUB_AUTHPROXY_CONTAINER_NAME}'…"
echo

docker start ${PHUB_AUTHPROXY_CONTAINER_NAME}
