# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { raise 'SECRET_KEY_BASE missing from env' } %>
  github_client_id: <%= ENV.fetch('GITHUB_CLIENT_ID') { raise 'GITHUB_CLIENT_ID missing from env' } %>
  github_client_secret: <%= ENV.fetch('GITHUB_CLIENT_SECRET') { raise 'GITHUB_CLIENT_SECRET missing from env' } %>


development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
