# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { raise 'SECRET_KEY_BASE missing from env' } %>

  github_client_id: <%= ENV.fetch('GITHUB_CLIENT_ID') { raise 'GITHUB_CLIENT_ID missing from env' } %>
  github_client_secret: <%= ENV.fetch('GITHUB_CLIENT_SECRET') { raise 'GITHUB_CLIENT_SECRET missing from env' } %>

  agent_github_token: <%= ENV.fetch('AGENT_GITHUB_TOKEN') { raise 'AGENT_GITHUB_TOKEN missing from env' } %>
  agent_github_org: <%= ENV.fetch('AGENT_GITHUB_ORG') { raise 'AGENT_GITHUB_ORG missing from env' } %>
  agent_github_org_main_team_id: <%= ENV.fetch('AGENT_GITHUB_ORG_MAIN_TEAM_ID') { raise 'AGENT_GITHUB_ORG_MAIN_TEAM_ID missing from env' } %>

  agent_keycloak_client_id: <%= ENV.fetch('AGENT_KEYCLOAK_CLIENT_ID') { raise 'AGENT_KEYCLOAK_CLIENT_ID missing from env' } %>
  agent_keycloak_client_secret: <%= ENV.fetch('AGENT_KEYCLOAK_CLIENT_SECRET') { raise 'AGENT_KEYCLOAK_CLIENT_SECRET missing from env' } %>
  agent_keycload_username: <%= ENV.fetch('AGENT_KEYCLOAK_USERNAME') { raise 'AGENT_KEYCLOAK_USERNAME missing from env' } %>
  agent_keycload_password: <%= ENV.fetch('AGENT_KEYCLOAK_PASSWORD') { raise 'AGENT_KEYCLOAK_PASSWORD missing from env' } %>
  agent_keycload_base_url: <%= ENV.fetch('AGENT_KEYCLOAK_BASE_URL') { raise 'AGENT_KEYCLOAK_BASE_URL missing from env' } %>
  agent_keycload_realm: <%= ENV.fetch('AGENT_KEYCLOAK_REALM') { raise 'AGENT_KEYCLOAK_REALM missing from env' } %>

  slack_webhook: <%= ENV.fetch('SLACK_WEBHOOK') { raise 'SLACK_WEBHOOK missing from env' } %>

  filestore_s3_region: <%= ENV.fetch('FILESTORE_S3_REGION') { raise 'FILESTORE_S3_REGION missing from env' } %>
  filestore_s3_bucket_name: <%= ENV.fetch('FILESTORE_S3_BUCKET_NAME') { raise 'FILESTORE_S3_BUCKET_NAME missing from env' } %>
  filestore_s3_access_key_id: <%= ENV.fetch('FILESTORE_S3_ACCESS_KEY_ID') { raise 'FILESTORE_S3_ACCESS_KEY_ID missing from env' } %>
  filestore_s3_secret_access_key: <%= ENV.fetch('FILESTORE_S3_SECRET_ACCESS_KEY') { raise 'FILESTORE_S3_SECRET_ACCESS_KEY missing from env' } %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
