source 'https://rubygems.org'

ruby '2.3.6'

gem 'rails', '~> 5.0.0', '>= 5.0.2'
gem 'pg', '~> 0.21.0'
gem 'puma', '~> 3.0'
gem 'jwt', '1.5.4'
gem 'hashie', '~> 3.4', '>= 3.4.6'
gem 'active_model_serializers', '~> 0.10.0'
gem 'activemodel-associations', '~> 0.2.0'
gem 'octokit', '~> 4.6', '>= 4.6.2'
gem 'friendly_id', '~> 5.2'
gem 'cancancan', '~> 2.1.2'
gem 'pg_search', '~> 2.0', '>= 2.0.1'
gem 'composite_primary_keys', '~> 9.0', '>= 9.0.6'
gem 'classy_hash', '~> 0.2.0'
gem 'attribute-defaults', '~> 0.8.0'
gem 'delayed_job', '~> 4.1', '>= 4.1.3'
gem 'delayed_job_active_record', '~> 4.1', '>= 4.1.2'
gem 'slack-notifier', '~> 2.2', '>= 2.2.2'
gem 'unread', '~> 0.9.1'
gem 'aws-sdk', '~> 2'
gem 'rinku', '~> 2.0', '>= 2.0.3'
gem 'faraday', '~> 0.11' # locked faraday at version matching one of octokit sub-depencies
gem 'hash-initializer', '~> 0.1.2'
gem 'kaminari', '~> 1.1', '>= 1.1.1'
gem 'api-pagination', '~> 4.7'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.7', '>= 3.7.0'
  gem 'rails-controller-testing', '~> 1.0'
  gem 'dotenv-rails', '~> 2.2', '>= 2.2.0'
  gem 'factory_girl_rails', '~> 4.8'
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.2'
end

group :development do
  gem 'listen', '~> 3.1.5'
  gem 'spring-watcher-listen', '~> 2.0.1'
end

group :test do
  gem 'timecop', '~> 0.9.1'
  gem 'with_model', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
