source 'https://rubygems.org'

ruby '2.3.3'

gem 'rails', '~> 5.0.0', '>= 5.0.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'jwt', '~> 1.5', '>= 1.5.4'
gem 'hashie', '~> 3.4', '>= 3.4.6'
gem 'active_model_serializers', '~> 0.10.0'
gem 'octokit', '~> 4.6', '>= 4.6.2'
gem 'gibberish', '~> 2.1'
gem 'friendly_id', '~> 5.2'
gem 'cancancan', '~> 1.15'
gem 'pg_search', '~> 2.0', '>= 2.0.1'
gem 'composite_primary_keys', '~> 9.0', '>= 9.0.6'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
  gem 'dotenv-rails', '~> 2.2', '>= 2.2.0'
  gem 'factory_girl_rails', '~> 4.8'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'timecop', '~> 0.8.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
