export const icons = function () {
  'ngInject';

  return {
    addToken: 'add_box',
    announcements: 'announcement',
    appSettings: 'settings',
    contactList: 'contacts',
    copy: 'content_copy',
    costsReports: 'attach_money',
    docs: 'description',
    docsSources: 'library_books',
    escalateToken: 'security',
    externalLink: 'link',
    faq: 'question_answer',
    featureFlags: 'flag',
    home: 'home',
    hubSetup: 'settings',
    identities: 'account_box',
    internalLink: 'input',
    kubernetesClusters: 'cloud_circle',
    kubernetesGroups: 'groups',
    kubernetesNamespaces: 'picture_in_picture_alt',
    kubernetesTokens: 'vpn_key',
    link: 'link',
    markAllRead: 'drafts',
    menu: 'menu',
    pinnedHelpEntries: 'low_priority',
    platformThemes: 'lens',
    projects: 'group_work',
    qaEntries: 'question_answer',
    revokeToken: 'delete_sweep',
    search: 'search',
    services: 'cloud_circle',
    supportRequests: 'live_help',
    syncTokens: 'cloud_upload',
    termsOfService: 'assignment',
    text: 'short_text',
    users: 'perm_identity'
  };
};
